name: Publish

on:
  push:
    branches:
      - main
    inputs:
      mpy_cross_versions:  # A json list of mpy-cross versions to generate releases for
        required: true
      branch:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5  # Only run 5 jobs at once so we don't get rate limited

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependancies
        id: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install mpy-cross==1.20.0

      - name: Build
        run: |
          mkdir build
          for f in $(find src/ -type f -name "*.py"); do mpy-cross -o build/$(basename $f .py).mpy $f; done

      - name: Get commit SHA
        id: get-commit-sha
        run: |
          echo "BRANCH=${{ github.event.inputs.branch }}"
          tag_sha=$(git rev-list -n 1 ${{ github.event.inputs.branch }})
          echo "TAG_SHA=$tag_sha" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: "Release ${{ matrix.tag }} for micropython-${{ matrix.version }}"
          tag: "micropython-${{ matrix.version }}-${{ matrix.tag }}"
          commit: ${{ steps.get-commit-sha.outputs.TAG_SHA }}
          artifacts: "build/*.mpy"
          skipIfReleaseExists: true
