name: Publish

on:
  push:
    branches:
      - main
    inputs:
      mpy_cross_versions:  # A json list of mpy-cross versions to generate releases for
        required: true

  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5  # Only run 5 jobs at once so we don't get rate limited
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependancies
        id: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install mpy-cross==1.20.0

      - name: Build
        run: |
          mkdir build
          cp src/package.json build
          for f in $(find src -type f -name "*.py"); do mpy-cross -o build/$(basename $f .py).mpy $f; done
          ls -l build

      - name: Get commit SHA
        id: get-commit-sha
        run: |
          tag_sha=$(git rev-list -n 1 main)
          echo "TAG_SHA=$tag_sha" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: "Release main for micropython-1.20.0"
          tag: "v1.1"
          commit: ${{ steps.get-commit-sha.outputs.TAG_SHA }}
          artifacts: "build/*.mpy,build/package.json"
          skipIfReleaseExists: true
